import { doctors, services } from '../data/clinicData';
import Icon from './Icon';

export function TreatmentSheet({ open, onClose, value, onSelect }) {
  return <div className={`sheet-overlay ${open ? 'active' : ''}`} onClick={(event) => event.target === event.currentTarget && onClose()}><div className="bottom-sheet"><div className="sheet-handle-bar" /><div className="sheet-header"><div><h3 className="sheet-title">Select Treatment</h3><p className="sheet-subtitle">Choose from all 16 dental services</p></div><button type="button" className="sheet-close-btn" onClick={onClose}><Icon name="x" size={18} /></button></div><div className="treatment-options-list">{services.map((service) => <button type="button" key={service.name} className={`treatment-option-card ${value === service.name ? 'selected' : ''}`} onClick={() => onSelect(service.name)}><div className="treatment-option-icon"><Icon name={service.icon} size={18} /></div><div className="treatment-option-info"><h4 className="treatment-opt-title">{service.displayName}</h4><p className="treatment-opt-sub">{service.category}</p></div>{value === service.name && <Icon name="check" size={17} />}</button>)}</div></div></div>;
}

export function TeamOverlay({ open, onClose }) {
  return <div className={`page-overlay ${open ? 'active' : ''}`}><div className="page-overlay-header"><button type="button" className="back-btn" onClick={onClose}><Icon name="arrow-left" size={16} /> Back</button><h3 className="page-overlay-heading">Our Medical Team</h3><div className="header-balance-spacer" /></div><div className="team-full-list">{doctors.map((doctor) => <div className="team-full-card" key={doctor.name}><img src={doctor.image.replace('w=800','w=500')} alt={doctor.name} /><div className="team-full-info"><span style={{ fontSize: '.68rem', fontWeight: 700, color: 'var(--teal)' }}>{doctor.role.toUpperCase()}</span><h4 style={{ fontSize: '1rem' }}>{doctor.name}</h4><p style={{ fontSize: '.78rem', color: 'var(--text-sub)' }}>{doctor.description}</p></div></div>)}</div></div>;
}

export function ServicesOverlay({ open, onClose, onBook }) {
  return <div className={`page-overlay ${open ? 'active' : ''}`}><div className="page-overlay-header"><button type="button" className="back-btn" onClick={onClose}><Icon name="arrow-left" size={16} /> Back</button><h3 className="page-overlay-heading">All 16 Specialized Services</h3><div className="header-balance-spacer" /></div><div className="catalogue-container"><div className="catalogue-grid">{services.map((service) => <div className="service-item-view" key={service.name}><div className="item-top"><div className="item-icon"><Icon name={service.icon} size={20} /></div><span className="item-badge">{service.category}</span></div><div className="item-content"><h3 className="item-title">{service.displayName}</h3><p className="item-desc">{service.description}</p></div><button type="button" className="item-book-btn" onClick={() => { onBook(service.name); onClose(); }}>Book Service</button></div>)}</div></div></div>;
}
